name: Playwright Tests

on:
  push:
  pull_request:
  workflow_dispatch:
  #schedule:
 #   - cron: '0 7 * * *'   # 2 AM Toronto time

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci --omit=optional

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # ✅ Install Allure CLI
      - name: Install Allure
        run: npm install -g allure-commandline --save-dev

      # ✅ Run tests (generate allure-results)
      - name: Run Playwright tests
        run: npx playwright test

      # ✅ Generate Allure Report
      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      # ✅ Upload report as artifact (so you can download from GitHub)
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # ✅ Deploy report to GitHub Pages (optional but powerful)
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report

      # ✅ Send Email with Report Link
      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAILUSERNAME }}
          password: ${{ secrets.EMAILPASSWORD }}
          subject: "Playwright Test Report"
          to: qa-teamahirwar@googlegroups.com
          from: ${{ secrets.EMAILUSERNAME }}
          secure: true
          body: |
            Playwright test execution completed.

            ✅ Status: ${{ job.status }}

            📊 Allure Report:
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/
